import { AppSettings }  from './AppSettings';

export interface signalDataInterface {
  scRSSI: string,
  scRSRP: string,
  scSINR: string,
  scRSRQ: string,
  scPCID: string,
  n1RSSI: string,
  n1RSRP: string,
  n1SINR: string,
  n1RSRQ: string,
  n1PCID: string,
  n2RSSI: string,
  n2RSRP: string,
  n2SINR: string,
  n2RSRQ: string,
  n2PCID: string,
  n3RSSI: string,
  n3RSRP: string,
  n3SINR: string,
  n3RSRQ: string,
  n3PCID: string,  
};

export interface signalColorInterface {
  scRSSI: string,
  scRSRP: string,
  scSINR: string,
  scRSRQ: string,
  n1RSSI: string,
  n1RSRP: string,
  n1SINR: string,
  n1RSRQ: string,
  n2RSSI: string,
  n2RSRP: string,
  n2SINR: string,
  n2RSRQ: string,
  n3RSSI: string,
  n3RSRP: string,
  n3SINR: string,
  n3RSRQ: string,
};

export interface markerInterface {  
  id: string,
  latitude: number, 
  longitude: number, 
  scRSSI: number, 
  scRSRP: number,
  scSINR: number,
  scRSRQ: number,
};

export interface markerInterfaceMongo {
  id: string,
  latitude: number, 
  longitude: number, 
  scRSSI: number, 
  scRSRP: number,
  scSINR: number,
  scRSRQ: number,
};

export interface retriveDataFromDBInterface {
  id: string,
  date: Date,
  username: string,
  imei: string,
  imsi: string,
  mode: string,
  band: string,
  latitude: number,
  longitude: number,
  scRSSI: string,
  scRSRP: string,
  scSINR: string,
  scRSRQ: string,
  scPCID: string,
  n1RSSI: string,
  n1RSRP: string,
  n1SINR: string,
  n1RSRQ: string,
  n1PCID: string,
  n2RSSI: string,
  n2RSRP: string,
  n2SINR: string,
  n2RSRQ: string,
  n2PCID: string,
  n3RSSI: string,
  n3RSRP: string,
  n3SINR: string,
  n3RSRQ: string,
  n3PCID: string,
}